#include "vm/platform_vm.h"

#include "vm/platform.h"
#include "vm/platform_bytecode.h"

#include <cstdint>
#include <string>
#include <unordered_map>

namespace torture::vm::platform_vm {

namespace pbc = ::torture::vm::platform_bytecode;

struct DispatchEntry {
    std::uint16_t id;
    const char* description;
};

#if TORTURE_PLATFORM_ID == TORTURE_PLATFORM_LINUX_X64
constexpr DispatchEntry kEntries[] = {
    {platform_bytecode::kOpcodeVerify,             "verify function fingerprint"},
    {platform_bytecode::kOpcodePushInteger,        "push integer constant"},
    {platform_bytecode::kOpcodePushString,         "push string constant"},
    {platform_bytecode::kOpcodePushNull,           "push null literal"},
    {platform_bytecode::kOpcodePushReference,      "push reference to local"},
    {platform_bytecode::kOpcodeDereference,        "dereference reference"},
    {platform_bytecode::kOpcodeFieldReference,     "compute field reference"},
    {platform_bytecode::kOpcodeLoad,               "load local value"},
    {platform_bytecode::kOpcodeStore,              "store local value"},
    {platform_bytecode::kOpcodeStoreDereference,   "store through reference"},
    {platform_bytecode::kOpcodeStorePointer,       "store function pointer"},
    {platform_bytecode::kOpcodePop,                "pop top of stack"},
    {platform_bytecode::kOpcodeAdd,                "integer add (default policy)"},
    {platform_bytecode::kOpcodeAddTrap,            "integer add with trap-on-overflow"},
    {platform_bytecode::kOpcodeAddWrap,            "integer add with wrap"},
    {platform_bytecode::kOpcodeAddSaturate,        "integer add with saturate"},
    {platform_bytecode::kOpcodeAddExtend,          "integer add with extend"},
    {platform_bytecode::kOpcodeSub,                "integer sub"},
    {platform_bytecode::kOpcodeSubTrap,            "integer sub trap"},
    {platform_bytecode::kOpcodeSubWrap,            "integer sub wrap"},
    {platform_bytecode::kOpcodeSubSaturate,        "integer sub saturate"},
    {platform_bytecode::kOpcodeSubExtend,          "integer sub extend"},
    {platform_bytecode::kOpcodeMul,                "integer mul"},
    {platform_bytecode::kOpcodeMulTrap,            "integer mul trap"},
    {platform_bytecode::kOpcodeMulWrap,            "integer mul wrap"},
    {platform_bytecode::kOpcodeMulSaturate,        "integer mul saturate"},
    {platform_bytecode::kOpcodeMulExtend,          "integer mul extend"},
    {platform_bytecode::kOpcodeDiv,                "integer div"},
    {platform_bytecode::kOpcodeDivTrap,            "integer div trap"},
    {platform_bytecode::kOpcodeDivWrap,            "integer div wrap"},
    {platform_bytecode::kOpcodeDivSaturate,        "integer div saturate"},
    {platform_bytecode::kOpcodeDivExtend,          "integer div extend"},
    {platform_bytecode::kOpcodeEqual,              "compare equal"},
    {platform_bytecode::kOpcodeNotEqual,           "compare not equal"},
    {platform_bytecode::kOpcodeLess,               "compare less"},
    {platform_bytecode::kOpcodeLessEqual,          "compare less equal"},
    {platform_bytecode::kOpcodeGreater,            "compare greater"},
    {platform_bytecode::kOpcodeGreaterEqual,       "compare greater equal"},
    {platform_bytecode::kOpcodeAnd,                "logical and"},
    {platform_bytecode::kOpcodeOr,                 "logical or"},
    {platform_bytecode::kOpcodeXor,                "logical xor"},
    {platform_bytecode::kOpcodeNand,               "logical nand"},
    {platform_bytecode::kOpcodeNor,                "logical nor"},
    {platform_bytecode::kOpcodeNot,                "logical not"},
    {platform_bytecode::kOpcodeJump,               "unconditional jump"},
    {platform_bytecode::kOpcodeJumpIfZero,         "jump if zero"},
    {platform_bytecode::kOpcodeCheckApproval,      "check approval gate"},
    {platform_bytecode::kOpcodeCheckLimits,        "check resource limits"},
    {platform_bytecode::kOpcodeCheckRole,          "check role"},
    {platform_bytecode::kOpcodeCheckRoleIndirect,  "check role via pointer"},
    {platform_bytecode::kOpcodeNullCheck,          "null function pointer check"},
    {platform_bytecode::kOpcodeAssert,             "proof obligation assert"},
    {platform_bytecode::kOpcodeCall,               "direct call"},
    {platform_bytecode::kOpcodeCallIndirect,       "indirect call"},
    {platform_bytecode::kOpcodeOutputInt,          "output integer"},
    {platform_bytecode::kOpcodeOutputChar,         "output character"},
    {platform_bytecode::kOpcodePrintLine,          "print line"},
    {platform_bytecode::kOpcodeInputInt,           "input integer"},
    {platform_bytecode::kOpcodeInputChar,          "input character"},
    {platform_bytecode::kOpcodeVerifyEcc,          "verify memory ECC"},
    {platform_bytecode::kOpcodeCopyMemory,         "copy memory"},
    {platform_bytecode::kOpcodeCompareMemory,      "compare memory"},
    {platform_bytecode::kOpcodeRole,               "role chain operation"},
    {platform_bytecode::kOpcodeOperatorInput,      "operator yes/no input"},
    {platform_bytecode::kOpcodeReturn,             "function return"},
    {platform_bytecode::kOpcodeHalt,               "halt VM"},
};
#elif TORTURE_PLATFORM_ID == TORTURE_PLATFORM_LINUX_X32
constexpr DispatchEntry kEntries[] = {
    {platform_bytecode::kOpcodeVerify,             "verify function fingerprint (linux-x32)"},
    {platform_bytecode::kOpcodePushInteger,        "push integer constant (linux-x32)"},
    {platform_bytecode::kOpcodePushString,         "push string constant (linux-x32)"},
    {platform_bytecode::kOpcodePushNull,           "push null literal (linux-x32)"},
    {platform_bytecode::kOpcodePushReference,      "push reference to local (linux-x32)"},
    {platform_bytecode::kOpcodeDereference,        "dereference reference (linux-x32)"},
    {platform_bytecode::kOpcodeFieldReference,     "compute field reference (linux-x32)"},
    {platform_bytecode::kOpcodeLoad,               "load local value (linux-x32)"},
    {platform_bytecode::kOpcodeStore,              "store local value (linux-x32)"},
    {platform_bytecode::kOpcodeStoreDereference,   "store through reference (linux-x32)"},
    {platform_bytecode::kOpcodeStorePointer,       "store function pointer (linux-x32)"},
    {platform_bytecode::kOpcodePop,                "pop top of stack (linux-x32)"},
    {platform_bytecode::kOpcodeAdd,                "integer add (linux-x32)"},
    {platform_bytecode::kOpcodeAddTrap,            "integer add trap (linux-x32)"},
    {platform_bytecode::kOpcodeAddWrap,            "integer add wrap (linux-x32)"},
    {platform_bytecode::kOpcodeAddSaturate,        "integer add saturate (linux-x32)"},
    {platform_bytecode::kOpcodeAddExtend,          "integer add extend (linux-x32)"},
    {platform_bytecode::kOpcodeSub,                "integer sub (linux-x32)"},
    {platform_bytecode::kOpcodeSubTrap,            "integer sub trap (linux-x32)"},
    {platform_bytecode::kOpcodeSubWrap,            "integer sub wrap (linux-x32)"},
    {platform_bytecode::kOpcodeSubSaturate,        "integer sub saturate (linux-x32)"},
    {platform_bytecode::kOpcodeSubExtend,          "integer sub extend (linux-x32)"},
    {platform_bytecode::kOpcodeMul,                "integer mul (linux-x32)"},
    {platform_bytecode::kOpcodeMulTrap,            "integer mul trap (linux-x32)"},
    {platform_bytecode::kOpcodeMulWrap,            "integer mul wrap (linux-x32)"},
    {platform_bytecode::kOpcodeMulSaturate,        "integer mul saturate (linux-x32)"},
    {platform_bytecode::kOpcodeMulExtend,          "integer mul extend (linux-x32)"},
    {platform_bytecode::kOpcodeDiv,                "integer div (linux-x32)"},
    {platform_bytecode::kOpcodeDivTrap,            "integer div trap (linux-x32)"},
    {platform_bytecode::kOpcodeDivWrap,            "integer div wrap (linux-x32)"},
    {platform_bytecode::kOpcodeDivSaturate,        "integer div saturate (linux-x32)"},
    {platform_bytecode::kOpcodeDivExtend,          "integer div extend (linux-x32)"},
    {platform_bytecode::kOpcodeEqual,              "compare equal (linux-x32)"},
    {platform_bytecode::kOpcodeNotEqual,           "compare not equal (linux-x32)"},
    {platform_bytecode::kOpcodeLess,               "compare less (linux-x32)"},
    {platform_bytecode::kOpcodeLessEqual,          "compare less equal (linux-x32)"},
    {platform_bytecode::kOpcodeGreater,            "compare greater (linux-x32)"},
    {platform_bytecode::kOpcodeGreaterEqual,       "compare greater equal (linux-x32)"},
    {platform_bytecode::kOpcodeAnd,                "logical and (linux-x32)"},
    {platform_bytecode::kOpcodeOr,                 "logical or (linux-x32)"},
    {platform_bytecode::kOpcodeXor,                "logical xor (linux-x32)"},
    {platform_bytecode::kOpcodeNand,               "logical nand (linux-x32)"},
    {platform_bytecode::kOpcodeNor,                "logical nor (linux-x32)"},
    {platform_bytecode::kOpcodeNot,                "logical not (linux-x32)"},
    {platform_bytecode::kOpcodeJump,               "unconditional jump (linux-x32)"},
    {platform_bytecode::kOpcodeJumpIfZero,         "jump if zero (linux-x32)"},
    {platform_bytecode::kOpcodeCheckApproval,      "check approval gate (linux-x32)"},
    {platform_bytecode::kOpcodeCheckLimits,        "check resource limits (linux-x32)"},
    {platform_bytecode::kOpcodeCheckRole,          "check role (linux-x32)"},
    {platform_bytecode::kOpcodeCheckRoleIndirect,  "check role via pointer (linux-x32)"},
    {platform_bytecode::kOpcodeNullCheck,          "null function pointer check (linux-x32)"},
    {platform_bytecode::kOpcodeAssert,             "proof obligation assert (linux-x32)"},
    {platform_bytecode::kOpcodeCall,               "direct call (linux-x32)"},
    {platform_bytecode::kOpcodeCallIndirect,       "indirect call (linux-x32)"},
    {platform_bytecode::kOpcodeOutputInt,          "output integer (linux-x32)"},
    {platform_bytecode::kOpcodeOutputChar,         "output character (linux-x32)"},
    {platform_bytecode::kOpcodePrintLine,          "print line (linux-x32)"},
    {platform_bytecode::kOpcodeInputInt,           "input integer (linux-x32)"},
    {platform_bytecode::kOpcodeInputChar,          "input character (linux-x32)"},
    {platform_bytecode::kOpcodeVerifyEcc,          "verify memory ECC (linux-x32)"},
    {platform_bytecode::kOpcodeCopyMemory,         "copy memory (linux-x32)"},
    {platform_bytecode::kOpcodeCompareMemory,      "compare memory (linux-x32)"},
    {platform_bytecode::kOpcodeRole,               "role chain operation (linux-x32)"},
    {platform_bytecode::kOpcodeOperatorInput,      "operator yes/no input (linux-x32)"},
    {platform_bytecode::kOpcodeReturn,             "function return (linux-x32)"},
    {platform_bytecode::kOpcodeHalt,               "halt VM (linux-x32)"},
};
#elif TORTURE_PLATFORM_ID == TORTURE_PLATFORM_LINUX_ARM32
constexpr DispatchEntry kEntries[] = {
    {platform_bytecode::kOpcodeVerify,             "verify function fingerprint (linux-arm32)"},
    {platform_bytecode::kOpcodePushInteger,        "push integer constant (linux-arm32)"},
    {platform_bytecode::kOpcodePushString,         "push string constant (linux-arm32)"},
    {platform_bytecode::kOpcodePushNull,           "push null literal (linux-arm32)"},
    {platform_bytecode::kOpcodePushReference,      "push reference to local (linux-arm32)"},
    {platform_bytecode::kOpcodeDereference,        "dereference reference (linux-arm32)"},
    {platform_bytecode::kOpcodeFieldReference,     "compute field reference (linux-arm32)"},
    {platform_bytecode::kOpcodeLoad,               "load local value (linux-arm32)"},
    {platform_bytecode::kOpcodeStore,              "store local value (linux-arm32)"},
    {platform_bytecode::kOpcodeStoreDereference,   "store through reference (linux-arm32)"},
    {platform_bytecode::kOpcodeStorePointer,       "store function pointer (linux-arm32)"},
    {platform_bytecode::kOpcodePop,                "pop top of stack (linux-arm32)"},
    {platform_bytecode::kOpcodeAdd,                "integer add (linux-arm32)"},
    {platform_bytecode::kOpcodeAddTrap,            "integer add trap (linux-arm32)"},
    {platform_bytecode::kOpcodeAddWrap,            "integer add wrap (linux-arm32)"},
    {platform_bytecode::kOpcodeAddSaturate,        "integer add saturate (linux-arm32)"},
    {platform_bytecode::kOpcodeAddExtend,          "integer add extend (linux-arm32)"},
    {platform_bytecode::kOpcodeSub,                "integer sub (linux-arm32)"},
    {platform_bytecode::kOpcodeSubTrap,            "integer sub trap (linux-arm32)"},
    {platform_bytecode::kOpcodeSubWrap,            "integer sub wrap (linux-arm32)"},
    {platform_bytecode::kOpcodeSubSaturate,        "integer sub saturate (linux-arm32)"},
    {platform_bytecode::kOpcodeSubExtend,          "integer sub extend (linux-arm32)"},
    {platform_bytecode::kOpcodeMul,                "integer mul (linux-arm32)"},
    {platform_bytecode::kOpcodeMulTrap,            "integer mul trap (linux-arm32)"},
    {platform_bytecode::kOpcodeMulWrap,            "integer mul wrap (linux-arm32)"},
    {platform_bytecode::kOpcodeMulSaturate,        "integer mul saturate (linux-arm32)"},
    {platform_bytecode::kOpcodeMulExtend,          "integer mul extend (linux-arm32)"},
    {platform_bytecode::kOpcodeDiv,                "integer div (linux-arm32)"},
    {platform_bytecode::kOpcodeDivTrap,            "integer div trap (linux-arm32)"},
    {platform_bytecode::kOpcodeDivWrap,            "integer div wrap (linux-arm32)"},
    {platform_bytecode::kOpcodeDivSaturate,        "integer div saturate (linux-arm32)"},
    {platform_bytecode::kOpcodeDivExtend,          "integer div extend (linux-arm32)"},
    {platform_bytecode::kOpcodeEqual,              "compare equal (linux-arm32)"},
    {platform_bytecode::kOpcodeNotEqual,           "compare not equal (linux-arm32)"},
    {platform_bytecode::kOpcodeLess,               "compare less (linux-arm32)"},
    {platform_bytecode::kOpcodeLessEqual,          "compare less equal (linux-arm32)"},
    {platform_bytecode::kOpcodeGreater,            "compare greater (linux-arm32)"},
    {platform_bytecode::kOpcodeGreaterEqual,       "compare greater equal (linux-arm32)"},
    {platform_bytecode::kOpcodeAnd,                "logical and (linux-arm32)"},
    {platform_bytecode::kOpcodeOr,                 "logical or (linux-arm32)"},
    {platform_bytecode::kOpcodeXor,                "logical xor (linux-arm32)"},
    {platform_bytecode::kOpcodeNand,               "logical nand (linux-arm32)"},
    {platform_bytecode::kOpcodeNor,                "logical nor (linux-arm32)"},
    {platform_bytecode::kOpcodeNot,                "logical not (linux-arm32)"},
    {platform_bytecode::kOpcodeJump,               "unconditional jump (linux-arm32)"},
    {platform_bytecode::kOpcodeJumpIfZero,         "jump if zero (linux-arm32)"},
    {platform_bytecode::kOpcodeCheckApproval,      "check approval gate (linux-arm32)"},
    {platform_bytecode::kOpcodeCheckLimits,        "check resource limits (linux-arm32)"},
    {platform_bytecode::kOpcodeCheckRole,          "check role (linux-arm32)"},
    {platform_bytecode::kOpcodeCheckRoleIndirect,  "check role via pointer (linux-arm32)"},
    {platform_bytecode::kOpcodeNullCheck,          "null function pointer check (linux-arm32)"},
    {platform_bytecode::kOpcodeAssert,             "proof obligation assert (linux-arm32)"},
    {platform_bytecode::kOpcodeCall,               "direct call (linux-arm32)"},
    {platform_bytecode::kOpcodeCallIndirect,       "indirect call (linux-arm32)"},
    {platform_bytecode::kOpcodeOutputInt,          "output integer (linux-arm32)"},
    {platform_bytecode::kOpcodeOutputChar,         "output character (linux-arm32)"},
    {platform_bytecode::kOpcodePrintLine,          "print line (linux-arm32)"},
    {platform_bytecode::kOpcodeInputInt,           "input integer (linux-arm32)"},
    {platform_bytecode::kOpcodeInputChar,          "input character (linux-arm32)"},
    {platform_bytecode::kOpcodeVerifyEcc,          "verify memory ECC (linux-arm32)"},
    {platform_bytecode::kOpcodeCopyMemory,         "copy memory (linux-arm32)"},
    {platform_bytecode::kOpcodeCompareMemory,      "compare memory (linux-arm32)"},
    {platform_bytecode::kOpcodeRole,               "role chain operation (linux-arm32)"},
    {platform_bytecode::kOpcodeOperatorInput,      "operator yes/no input (linux-arm32)"},
    {platform_bytecode::kOpcodeReturn,             "function return (linux-arm32)"},
    {platform_bytecode::kOpcodeHalt,               "halt VM (linux-arm32)"},
};
#elif TORTURE_PLATFORM_ID == TORTURE_PLATFORM_LINUX_ARM64
constexpr DispatchEntry kEntries[] = {
    {platform_bytecode::kOpcodeVerify,             "verify function fingerprint (linux-arm64)"},
    {platform_bytecode::kOpcodePushInteger,        "push integer constant (linux-arm64)"},
    {platform_bytecode::kOpcodePushString,         "push string constant (linux-arm64)"},
    {platform_bytecode::kOpcodePushNull,           "push null literal (linux-arm64)"},
    {platform_bytecode::kOpcodePushReference,      "push reference to local (linux-arm64)"},
    {platform_bytecode::kOpcodeDereference,        "dereference reference (linux-arm64)"},
    {platform_bytecode::kOpcodeFieldReference,     "compute field reference (linux-arm64)"},
    {platform_bytecode::kOpcodeLoad,               "load local value (linux-arm64)"},
    {platform_bytecode::kOpcodeStore,              "store local value (linux-arm64)"},
    {platform_bytecode::kOpcodeStoreDereference,   "store through reference (linux-arm64)"},
    {platform_bytecode::kOpcodeStorePointer,       "store function pointer (linux-arm64)"},
    {platform_bytecode::kOpcodePop,                "pop top of stack (linux-arm64)"},
    {platform_bytecode::kOpcodeAdd,                "integer add (linux-arm64)"},
    {platform_bytecode::kOpcodeAddTrap,            "integer add trap (linux-arm64)"},
    {platform_bytecode::kOpcodeAddWrap,            "integer add wrap (linux-arm64)"},
    {platform_bytecode::kOpcodeAddSaturate,        "integer add saturate (linux-arm64)"},
    {platform_bytecode::kOpcodeAddExtend,          "integer add extend (linux-arm64)"},
    {platform_bytecode::kOpcodeSub,                "integer sub (linux-arm64)"},
    {platform_bytecode::kOpcodeSubTrap,            "integer sub trap (linux-arm64)"},
    {platform_bytecode::kOpcodeSubWrap,            "integer sub wrap (linux-arm64)"},
    {platform_bytecode::kOpcodeSubSaturate,        "integer sub saturate (linux-arm64)"},
    {platform_bytecode::kOpcodeSubExtend,          "integer sub extend (linux-arm64)"},
    {platform_bytecode::kOpcodeMul,                "integer mul (linux-arm64)"},
    {platform_bytecode::kOpcodeMulTrap,            "integer mul trap (linux-arm64)"},
    {platform_bytecode::kOpcodeMulWrap,            "integer mul wrap (linux-arm64)"},
    {platform_bytecode::kOpcodeMulSaturate,        "integer mul saturate (linux-arm64)"},
    {platform_bytecode::kOpcodeMulExtend,          "integer mul extend (linux-arm64)"},
    {platform_bytecode::kOpcodeDiv,                "integer div (linux-arm64)"},
    {platform_bytecode::kOpcodeDivTrap,            "integer div trap (linux-arm64)"},
    {platform_bytecode::kOpcodeDivWrap,            "integer div wrap (linux-arm64)"},
    {platform_bytecode::kOpcodeDivSaturate,        "integer div saturate (linux-arm64)"},
    {platform_bytecode::kOpcodeDivExtend,          "integer div extend (linux-arm64)"},
    {platform_bytecode::kOpcodeEqual,              "compare equal (linux-arm64)"},
    {platform_bytecode::kOpcodeNotEqual,           "compare not equal (linux-arm64)"},
    {platform_bytecode::kOpcodeLess,               "compare less (linux-arm64)"},
    {platform_bytecode::kOpcodeLessEqual,          "compare less equal (linux-arm64)"},
    {platform_bytecode::kOpcodeGreater,            "compare greater (linux-arm64)"},
    {platform_bytecode::kOpcodeGreaterEqual,       "compare greater equal (linux-arm64)"},
    {platform_bytecode::kOpcodeAnd,                "logical and (linux-arm64)"},
    {platform_bytecode::kOpcodeOr,                 "logical or (linux-arm64)"},
    {platform_bytecode::kOpcodeXor,                "logical xor (linux-arm64)"},
    {platform_bytecode::kOpcodeNand,               "logical nand (linux-arm64)"},
    {platform_bytecode::kOpcodeNor,                "logical nor (linux-arm64)"},
    {platform_bytecode::kOpcodeNot,                "logical not (linux-arm64)"},
    {platform_bytecode::kOpcodeJump,               "unconditional jump (linux-arm64)"},
    {platform_bytecode::kOpcodeJumpIfZero,         "jump if zero (linux-arm64)"},
    {platform_bytecode::kOpcodeCheckApproval,      "check approval gate (linux-arm64)"},
    {platform_bytecode::kOpcodeCheckLimits,        "check resource limits (linux-arm64)"},
    {platform_bytecode::kOpcodeCheckRole,          "check role (linux-arm64)"},
    {platform_bytecode::kOpcodeCheckRoleIndirect,  "check role via pointer (linux-arm64)"},
    {platform_bytecode::kOpcodeNullCheck,          "null function pointer check (linux-arm64)"},
    {platform_bytecode::kOpcodeAssert,             "proof obligation assert (linux-arm64)"},
    {platform_bytecode::kOpcodeCall,               "direct call (linux-arm64)"},
    {platform_bytecode::kOpcodeCallIndirect,       "indirect call (linux-arm64)"},
    {platform_bytecode::kOpcodeOutputInt,          "output integer (linux-arm64)"},
    {platform_bytecode::kOpcodeOutputChar,         "output character (linux-arm64)"},
    {platform_bytecode::kOpcodePrintLine,          "print line (linux-arm64)"},
    {platform_bytecode::kOpcodeInputInt,           "input integer (linux-arm64)"},
    {platform_bytecode::kOpcodeInputChar,          "input character (linux-arm64)"},
    {platform_bytecode::kOpcodeVerifyEcc,          "verify memory ECC (linux-arm64)"},
    {platform_bytecode::kOpcodeCopyMemory,         "copy memory (linux-arm64)"},
    {platform_bytecode::kOpcodeCompareMemory,      "compare memory (linux-arm64)"},
    {platform_bytecode::kOpcodeRole,               "role chain operation (linux-arm64)"},
    {platform_bytecode::kOpcodeOperatorInput,      "operator yes/no input (linux-arm64)"},
    {platform_bytecode::kOpcodeReturn,             "function return (linux-arm64)"},
    {platform_bytecode::kOpcodeHalt,               "halt VM (linux-arm64)"},
};
#elif TORTURE_PLATFORM_ID == TORTURE_PLATFORM_WINDOWS_X86
constexpr DispatchEntry kEntries[] = {
    {platform_bytecode::kOpcodeVerify,             "verify function fingerprint (windows-x86)"},
    {platform_bytecode::kOpcodePushInteger,        "push integer constant (windows-x86)"},
    {platform_bytecode::kOpcodePushString,         "push string constant (windows-x86)"},
    {platform_bytecode::kOpcodePushNull,           "push null literal (windows-x86)"},
    {platform_bytecode::kOpcodePushReference,      "push reference to local (windows-x86)"},
    {platform_bytecode::kOpcodeDereference,        "dereference reference (windows-x86)"},
    {platform_bytecode::kOpcodeFieldReference,     "compute field reference (windows-x86)"},
    {platform_bytecode::kOpcodeLoad,               "load local value (windows-x86)"},
    {platform_bytecode::kOpcodeStore,              "store local value (windows-x86)"},
    {platform_bytecode::kOpcodeStoreDereference,   "store through reference (windows-x86)"},
    {platform_bytecode::kOpcodeStorePointer,       "store function pointer (windows-x86)"},
    {platform_bytecode::kOpcodePop,                "pop top of stack (windows-x86)"},
    {platform_bytecode::kOpcodeAdd,                "integer add (windows-x86)"},
    {platform_bytecode::kOpcodeAddTrap,            "integer add trap (windows-x86)"},
    {platform_bytecode::kOpcodeAddWrap,            "integer add wrap (windows-x86)"},
    {platform_bytecode::kOpcodeAddSaturate,        "integer add saturate (windows-x86)"},
    {platform_bytecode::kOpcodeAddExtend,          "integer add extend (windows-x86)"},
    {platform_bytecode::kOpcodeSub,                "integer sub (windows-x86)"},
    {platform_bytecode::kOpcodeSubTrap,            "integer sub trap (windows-x86)"},
    {platform_bytecode::kOpcodeSubWrap,            "integer sub wrap (windows-x86)"},
    {platform_bytecode::kOpcodeSubSaturate,        "integer sub saturate (windows-x86)"},
    {platform_bytecode::kOpcodeSubExtend,          "integer sub extend (windows-x86)"},
    {platform_bytecode::kOpcodeMul,                "integer mul (windows-x86)"},
    {platform_bytecode::kOpcodeMulTrap,            "integer mul trap (windows-x86)"},
    {platform_bytecode::kOpcodeMulWrap,            "integer mul wrap (windows-x86)"},
    {platform_bytecode::kOpcodeMulSaturate,        "integer mul saturate (windows-x86)"},
    {platform_bytecode::kOpcodeMulExtend,          "integer mul extend (windows-x86)"},
    {platform_bytecode::kOpcodeDiv,                "integer div (windows-x86)"},
    {platform_bytecode::kOpcodeDivTrap,            "integer div trap (windows-x86)"},
    {platform_bytecode::kOpcodeDivWrap,            "integer div wrap (windows-x86)"},
    {platform_bytecode::kOpcodeDivSaturate,        "integer div saturate (windows-x86)"},
    {platform_bytecode::kOpcodeDivExtend,          "integer div extend (windows-x86)"},
    {platform_bytecode::kOpcodeEqual,              "compare equal (windows-x86)"},
    {platform_bytecode::kOpcodeNotEqual,           "compare not equal (windows-x86)"},
    {platform_bytecode::kOpcodeLess,               "compare less (windows-x86)"},
    {platform_bytecode::kOpcodeLessEqual,          "compare less equal (windows-x86)"},
    {platform_bytecode::kOpcodeGreater,            "compare greater (windows-x86)"},
    {platform_bytecode::kOpcodeGreaterEqual,       "compare greater equal (windows-x86)"},
    {platform_bytecode::kOpcodeAnd,                "logical and (windows-x86)"},
    {platform_bytecode::kOpcodeOr,                 "logical or (windows-x86)"},
    {platform_bytecode::kOpcodeXor,                "logical xor (windows-x86)"},
    {platform_bytecode::kOpcodeNand,               "logical nand (windows-x86)"},
    {platform_bytecode::kOpcodeNor,                "logical nor (windows-x86)"},
    {platform_bytecode::kOpcodeNot,                "logical not (windows-x86)"},
    {platform_bytecode::kOpcodeJump,               "unconditional jump (windows-x86)"},
    {platform_bytecode::kOpcodeJumpIfZero,         "jump if zero (windows-x86)"},
    {platform_bytecode::kOpcodeCheckApproval,      "check approval gate (windows-x86)"},
    {platform_bytecode::kOpcodeCheckLimits,        "check resource limits (windows-x86)"},
    {platform_bytecode::kOpcodeCheckRole,          "check role (windows-x86)"},
    {platform_bytecode::kOpcodeCheckRoleIndirect,  "check role via pointer (windows-x86)"},
    {platform_bytecode::kOpcodeNullCheck,          "null function pointer check (windows-x86)"},
    {platform_bytecode::kOpcodeAssert,             "proof obligation assert (windows-x86)"},
    {platform_bytecode::kOpcodeCall,               "direct call (windows-x86)"},
    {platform_bytecode::kOpcodeCallIndirect,       "indirect call (windows-x86)"},
    {platform_bytecode::kOpcodeOutputInt,          "output integer (windows-x86)"},
    {platform_bytecode::kOpcodeOutputChar,         "output character (windows-x86)"},
    {platform_bytecode::kOpcodePrintLine,          "print line (windows-x86)"},
    {platform_bytecode::kOpcodeInputInt,           "input integer (windows-x86)"},
    {platform_bytecode::kOpcodeInputChar,          "input character (windows-x86)"},
    {platform_bytecode::kOpcodeVerifyEcc,          "verify memory ECC (windows-x86)"},
    {platform_bytecode::kOpcodeCopyMemory,         "copy memory (windows-x86)"},
    {platform_bytecode::kOpcodeCompareMemory,      "compare memory (windows-x86)"},
    {platform_bytecode::kOpcodeRole,               "role chain operation (windows-x86)"},
    {platform_bytecode::kOpcodeOperatorInput,      "operator yes/no input (windows-x86)"},
    {platform_bytecode::kOpcodeReturn,             "function return (windows-x86)"},
    {platform_bytecode::kOpcodeHalt,               "halt VM (windows-x86)"},
};
#elif TORTURE_PLATFORM_ID == TORTURE_PLATFORM_WINDOWS_X64
constexpr DispatchEntry kEntries[] = {
    {platform_bytecode::kOpcodeVerify,             "verify function fingerprint (windows-x64)"},
    {platform_bytecode::kOpcodePushInteger,        "push integer constant (windows-x64)"},
    {platform_bytecode::kOpcodePushString,         "push string constant (windows-x64)"},
    {platform_bytecode::kOpcodePushNull,           "push null literal (windows-x64)"},
    {platform_bytecode::kOpcodePushReference,      "push reference to local (windows-x64)"},
    {platform_bytecode::kOpcodeDereference,        "dereference reference (windows-x64)"},
    {platform_bytecode::kOpcodeFieldReference,     "compute field reference (windows-x64)"},
    {platform_bytecode::kOpcodeLoad,               "load local value (windows-x64)"},
    {platform_bytecode::kOpcodeStore,              "store local value (windows-x64)"},
    {platform_bytecode::kOpcodeStoreDereference,   "store through reference (windows-x64)"},
    {platform_bytecode::kOpcodeStorePointer,       "store function pointer (windows-x64)"},
    {platform_bytecode::kOpcodePop,                "pop top of stack (windows-x64)"},
    {platform_bytecode::kOpcodeAdd,                "integer add (windows-x64)"},
    {platform_bytecode::kOpcodeAddTrap,            "integer add trap (windows-x64)"},
    {platform_bytecode::kOpcodeAddWrap,            "integer add wrap (windows-x64)"},
    {platform_bytecode::kOpcodeAddSaturate,        "integer add saturate (windows-x64)"},
    {platform_bytecode::kOpcodeAddExtend,          "integer add extend (windows-x64)"},
    {platform_bytecode::kOpcodeSub,                "integer sub (windows-x64)"},
    {platform_bytecode::kOpcodeSubTrap,            "integer sub trap (windows-x64)"},
    {platform_bytecode::kOpcodeSubWrap,            "integer sub wrap (windows-x64)"},
    {platform_bytecode::kOpcodeSubSaturate,        "integer sub saturate (windows-x64)"},
    {platform_bytecode::kOpcodeSubExtend,          "integer sub extend (windows-x64)"},
    {platform_bytecode::kOpcodeMul,                "integer mul (windows-x64)"},
    {platform_bytecode::kOpcodeMulTrap,            "integer mul trap (windows-x64)"},
    {platform_bytecode::kOpcodeMulWrap,            "integer mul wrap (windows-x64)"},
    {platform_bytecode::kOpcodeMulSaturate,        "integer mul saturate (windows-x64)"},
    {platform_bytecode::kOpcodeMulExtend,          "integer mul extend (windows-x64)"},
    {platform_bytecode::kOpcodeDiv,                "integer div (windows-x64)"},
    {platform_bytecode::kOpcodeDivTrap,            "integer div trap (windows-x64)"},
    {platform_bytecode::kOpcodeDivWrap,            "integer div wrap (windows-x64)"},
    {platform_bytecode::kOpcodeDivSaturate,        "integer div saturate (windows-x64)"},
    {platform_bytecode::kOpcodeDivExtend,          "integer div extend (windows-x64)"},
    {platform_bytecode::kOpcodeEqual,              "compare equal (windows-x64)"},
    {platform_bytecode::kOpcodeNotEqual,           "compare not equal (windows-x64)"},
    {platform_bytecode::kOpcodeLess,               "compare less (windows-x64)"},
    {platform_bytecode::kOpcodeLessEqual,          "compare less equal (windows-x64)"},
    {platform_bytecode::kOpcodeGreater,            "compare greater (windows-x64)"},
    {platform_bytecode::kOpcodeGreaterEqual,       "compare greater equal (windows-x64)"},
    {platform_bytecode::kOpcodeAnd,                "logical and (windows-x64)"},
    {platform_bytecode::kOpcodeOr,                 "logical or (windows-x64)"},
    {platform_bytecode::kOpcodeXor,                "logical xor (windows-x64)"},
    {platform_bytecode::kOpcodeNand,               "logical nand (windows-x64)"},
    {platform_bytecode::kOpcodeNor,                "logical nor (windows-x64)"},
    {platform_bytecode::kOpcodeNot,                "logical not (windows-x64)"},
    {platform_bytecode::kOpcodeJump,               "unconditional jump (windows-x64)"},
    {platform_bytecode::kOpcodeJumpIfZero,         "jump if zero (windows-x64)"},
    {platform_bytecode::kOpcodeCheckApproval,      "check approval gate (windows-x64)"},
    {platform_bytecode::kOpcodeCheckLimits,        "check resource limits (windows-x64)"},
    {platform_bytecode::kOpcodeCheckRole,          "check role (windows-x64)"},
    {platform_bytecode::kOpcodeCheckRoleIndirect,  "check role via pointer (windows-x64)"},
    {platform_bytecode::kOpcodeNullCheck,          "null function pointer check (windows-x64)"},
    {platform_bytecode::kOpcodeAssert,             "proof obligation assert (windows-x64)"},
    {platform_bytecode::kOpcodeCall,               "direct call (windows-x64)"},
    {platform_bytecode::kOpcodeCallIndirect,       "indirect call (windows-x64)"},
    {platform_bytecode::kOpcodeOutputInt,          "output integer (windows-x64)"},
    {platform_bytecode::kOpcodeOutputChar,         "output character (windows-x64)"},
    {platform_bytecode::kOpcodePrintLine,          "print line (windows-x64)"},
    {platform_bytecode::kOpcodeInputInt,           "input integer (windows-x64)"},
    {platform_bytecode::kOpcodeInputChar,          "input character (windows-x64)"},
    {platform_bytecode::kOpcodeVerifyEcc,          "verify memory ECC (windows-x64)"},
    {platform_bytecode::kOpcodeCopyMemory,         "copy memory (windows-x64)"},
    {platform_bytecode::kOpcodeCompareMemory,      "compare memory (windows-x64)"},
    {platform_bytecode::kOpcodeRole,               "role chain operation (windows-x64)"},
    {platform_bytecode::kOpcodeOperatorInput,      "operator yes/no input (windows-x64)"},
    {platform_bytecode::kOpcodeReturn,             "function return (windows-x64)"},
    {platform_bytecode::kOpcodeHalt,               "halt VM (windows-x64)"},
};
#elif TORTURE_PLATFORM_ID == TORTURE_PLATFORM_WINDOWS_ARM32
constexpr DispatchEntry kEntries[] = {
    {platform_bytecode::kOpcodeVerify,             "verify function fingerprint (windows-arm32)"},
    {platform_bytecode::kOpcodePushInteger,        "push integer constant (windows-arm32)"},
    {platform_bytecode::kOpcodePushString,         "push string constant (windows-arm32)"},
    {platform_bytecode::kOpcodePushNull,           "push null literal (windows-arm32)"},
    {platform_bytecode::kOpcodePushReference,      "push reference to local (windows-arm32)"},
    {platform_bytecode::kOpcodeDereference,        "dereference reference (windows-arm32)"},
    {platform_bytecode::kOpcodeFieldReference,     "compute field reference (windows-arm32)"},
    {platform_bytecode::kOpcodeLoad,               "load local value (windows-arm32)"},
    {platform_bytecode::kOpcodeStore,              "store local value (windows-arm32)"},
    {platform_bytecode::kOpcodeStoreDereference,   "store through reference (windows-arm32)"},
    {platform_bytecode::kOpcodeStorePointer,       "store function pointer (windows-arm32)"},
    {platform_bytecode::kOpcodePop,                "pop top of stack (windows-arm32)"},
    {platform_bytecode::kOpcodeAdd,                "integer add (windows-arm32)"},
    {platform_bytecode::kOpcodeAddTrap,            "integer add trap (windows-arm32)"},
    {platform_bytecode::kOpcodeAddWrap,            "integer add wrap (windows-arm32)"},
    {platform_bytecode::kOpcodeAddSaturate,        "integer add saturate (windows-arm32)"},
    {platform_bytecode::kOpcodeAddExtend,          "integer add extend (windows-arm32)"},
    {platform_bytecode::kOpcodeSub,                "integer sub (windows-arm32)"},
    {platform_bytecode::kOpcodeSubTrap,            "integer sub trap (windows-arm32)"},
    {platform_bytecode::kOpcodeSubWrap,            "integer sub wrap (windows-arm32)"},
    {platform_bytecode::kOpcodeSubSaturate,        "integer sub saturate (windows-arm32)"},
    {platform_bytecode::kOpcodeSubExtend,          "integer sub extend (windows-arm32)"},
    {platform_bytecode::kOpcodeMul,                "integer mul (windows-arm32)"},
    {platform_bytecode::kOpcodeMulTrap,            "integer mul trap (windows-arm32)"},
    {platform_bytecode::kOpcodeMulWrap,            "integer mul wrap (windows-arm32)"},
    {platform_bytecode::kOpcodeMulSaturate,        "integer mul saturate (windows-arm32)"},
    {platform_bytecode::kOpcodeMulExtend,          "integer mul extend (windows-arm32)"},
    {platform_bytecode::kOpcodeDiv,                "integer div (windows-arm32)"},
    {platform_bytecode::kOpcodeDivTrap,            "integer div trap (windows-arm32)"},
    {platform_bytecode::kOpcodeDivWrap,            "integer div wrap (windows-arm32)"},
    {platform_bytecode::kOpcodeDivSaturate,        "integer div saturate (windows-arm32)"},
    {platform_bytecode::kOpcodeDivExtend,          "integer div extend (windows-arm32)"},
    {platform_bytecode::kOpcodeEqual,              "compare equal (windows-arm32)"},
    {platform_bytecode::kOpcodeNotEqual,           "compare not equal (windows-arm32)"},
    {platform_bytecode::kOpcodeLess,               "compare less (windows-arm32)"},
    {platform_bytecode::kOpcodeLessEqual,          "compare less equal (windows-arm32)"},
    {platform_bytecode::kOpcodeGreater,            "compare greater (windows-arm32)"},
    {platform_bytecode::kOpcodeGreaterEqual,       "compare greater equal (windows-arm32)"},
    {platform_bytecode::kOpcodeAnd,                "logical and (windows-arm32)"},
    {platform_bytecode::kOpcodeOr,                 "logical or (windows-arm32)"},
    {platform_bytecode::kOpcodeXor,                "logical xor (windows-arm32)"},
    {platform_bytecode::kOpcodeNand,               "logical nand (windows-arm32)"},
    {platform_bytecode::kOpcodeNor,                "logical nor (windows-arm32)"},
    {platform_bytecode::kOpcodeNot,                "logical not (windows-arm32)"},
    {platform_bytecode::kOpcodeJump,               "unconditional jump (windows-arm32)"},
    {platform_bytecode::kOpcodeJumpIfZero,         "jump if zero (windows-arm32)"},
    {platform_bytecode::kOpcodeCheckApproval,      "check approval gate (windows-arm32)"},
    {platform_bytecode::kOpcodeCheckLimits,        "check resource limits (windows-arm32)"},
    {platform_bytecode::kOpcodeCheckRole,          "check role (windows-arm32)"},
    {platform_bytecode::kOpcodeCheckRoleIndirect,  "check role via pointer (windows-arm32)"},
    {platform_bytecode::kOpcodeNullCheck,          "null function pointer check (windows-arm32)"},
    {platform_bytecode::kOpcodeAssert,             "proof obligation assert (windows-arm32)"},
    {platform_bytecode::kOpcodeCall,               "direct call (windows-arm32)"},
    {platform_bytecode::kOpcodeCallIndirect,       "indirect call (windows-arm32)"},
    {platform_bytecode::kOpcodeOutputInt,          "output integer (windows-arm32)"},
    {platform_bytecode::kOpcodeOutputChar,         "output character (windows-arm32)"},
    {platform_bytecode::kOpcodePrintLine,          "print line (windows-arm32)"},
    {platform_bytecode::kOpcodeInputInt,           "input integer (windows-arm32)"},
    {platform_bytecode::kOpcodeInputChar,          "input character (windows-arm32)"},
    {platform_bytecode::kOpcodeVerifyEcc,          "verify memory ECC (windows-arm32)"},
    {platform_bytecode::kOpcodeCopyMemory,         "copy memory (windows-arm32)"},
    {platform_bytecode::kOpcodeCompareMemory,      "compare memory (windows-arm32)"},
    {platform_bytecode::kOpcodeRole,               "role chain operation (windows-arm32)"},
    {platform_bytecode::kOpcodeOperatorInput,      "operator yes/no input (windows-arm32)"},
    {platform_bytecode::kOpcodeReturn,             "function return (windows-arm32)"},
    {platform_bytecode::kOpcodeHalt,               "halt VM (windows-arm32)"},
};
#elif TORTURE_PLATFORM_ID == TORTURE_PLATFORM_WINDOWS_ARM64
constexpr DispatchEntry kEntries[] = {
    {platform_bytecode::kOpcodeVerify,             "verify function fingerprint (windows-arm64)"},
    {platform_bytecode::kOpcodePushInteger,        "push integer constant (windows-arm64)"},
    {platform_bytecode::kOpcodePushString,         "push string constant (windows-arm64)"},
    {platform_bytecode::kOpcodePushNull,           "push null literal (windows-arm64)"},
    {platform_bytecode::kOpcodePushReference,      "push reference to local (windows-arm64)"},
    {platform_bytecode::kOpcodeDereference,        "dereference reference (windows-arm64)"},
    {platform_bytecode::kOpcodeFieldReference,     "compute field reference (windows-arm64)"},
    {platform_bytecode::kOpcodeLoad,               "load local value (windows-arm64)"},
    {platform_bytecode::kOpcodeStore,              "store local value (windows-arm64)"},
    {platform_bytecode::kOpcodeStoreDereference,   "store through reference (windows-arm64)"},
    {platform_bytecode::kOpcodeStorePointer,       "store function pointer (windows-arm64)"},
    {platform_bytecode::kOpcodePop,                "pop top of stack (windows-arm64)"},
    {platform_bytecode::kOpcodeAdd,                "integer add (windows-arm64)"},
    {platform_bytecode::kOpcodeAddTrap,            "integer add trap (windows-arm64)"},
    {platform_bytecode::kOpcodeAddWrap,            "integer add wrap (windows-arm64)"},
    {platform_bytecode::kOpcodeAddSaturate,        "integer add saturate (windows-arm64)"},
    {platform_bytecode::kOpcodeAddExtend,          "integer add extend (windows-arm64)"},
    {platform_bytecode::kOpcodeSub,                "integer sub (windows-arm64)"},
    {platform_bytecode::kOpcodeSubTrap,            "integer sub trap (windows-arm64)"},
    {platform_bytecode::kOpcodeSubWrap,            "integer sub wrap (windows-arm64)"},
    {platform_bytecode::kOpcodeSubSaturate,        "integer sub saturate (windows-arm64)"},
    {platform_bytecode::kOpcodeSubExtend,          "integer sub extend (windows-arm64)"},
    {platform_bytecode::kOpcodeMul,                "integer mul (windows-arm64)"},
    {platform_bytecode::kOpcodeMulTrap,            "integer mul trap (windows-arm64)"},
    {platform_bytecode::kOpcodeMulWrap,            "integer mul wrap (windows-arm64)"},
    {platform_bytecode::kOpcodeMulSaturate,        "integer mul saturate (windows-arm64)"},
    {platform_bytecode::kOpcodeMulExtend,          "integer mul extend (windows-arm64)"},
    {platform_bytecode::kOpcodeDiv,                "integer div (windows-arm64)"},
    {platform_bytecode::kOpcodeDivTrap,            "integer div trap (windows-arm64)"},
    {platform_bytecode::kOpcodeDivWrap,            "integer div wrap (windows-arm64)"},
    {platform_bytecode::kOpcodeDivSaturate,        "integer div saturate (windows-arm64)"},
    {platform_bytecode::kOpcodeDivExtend,          "integer div extend (windows-arm64)"},
    {platform_bytecode::kOpcodeEqual,              "compare equal (windows-arm64)"},
    {platform_bytecode::kOpcodeNotEqual,           "compare not equal (windows-arm64)"},
    {platform_bytecode::kOpcodeLess,               "compare less (windows-arm64)"},
    {platform_bytecode::kOpcodeLessEqual,          "compare less equal (windows-arm64)"},
    {platform_bytecode::kOpcodeGreater,            "compare greater (windows-arm64)"},
    {platform_bytecode::kOpcodeGreaterEqual,       "compare greater equal (windows-arm64)"},
    {platform_bytecode::kOpcodeAnd,                "logical and (windows-arm64)"},
    {platform_bytecode::kOpcodeOr,                 "logical or (windows-arm64)"},
    {platform_bytecode::kOpcodeXor,                "logical xor (windows-arm64)"},
    {platform_bytecode::kOpcodeNand,               "logical nand (windows-arm64)"},
    {platform_bytecode::kOpcodeNor,                "logical nor (windows-arm64)"},
    {platform_bytecode::kOpcodeNot,                "logical not (windows-arm64)"},
    {platform_bytecode::kOpcodeJump,               "unconditional jump (windows-arm64)"},
    {platform_bytecode::kOpcodeJumpIfZero,         "jump if zero (windows-arm64)"},
    {platform_bytecode::kOpcodeCheckApproval,      "check approval gate (windows-arm64)"},
    {platform_bytecode::kOpcodeCheckLimits,        "check resource limits (windows-arm64)"},
    {platform_bytecode::kOpcodeCheckRole,          "check role (windows-arm64)"},
    {platform_bytecode::kOpcodeCheckRoleIndirect,  "check role via pointer (windows-arm64)"},
    {platform_bytecode::kOpcodeNullCheck,          "null function pointer check (windows-arm64)"},
    {platform_bytecode::kOpcodeAssert,             "proof obligation assert (windows-arm64)"},
    {platform_bytecode::kOpcodeCall,               "direct call (windows-arm64)"},
    {platform_bytecode::kOpcodeCallIndirect,       "indirect call (windows-arm64)"},
    {platform_bytecode::kOpcodeOutputInt,          "output integer (windows-arm64)"},
    {platform_bytecode::kOpcodeOutputChar,         "output character (windows-arm64)"},
    {platform_bytecode::kOpcodePrintLine,          "print line (windows-arm64)"},
    {platform_bytecode::kOpcodeInputInt,           "input integer (windows-arm64)"},
    {platform_bytecode::kOpcodeInputChar,          "input character (windows-arm64)"},
    {platform_bytecode::kOpcodeVerifyEcc,          "verify memory ECC (windows-arm64)"},
    {platform_bytecode::kOpcodeCopyMemory,         "copy memory (windows-arm64)"},
    {platform_bytecode::kOpcodeCompareMemory,      "compare memory (windows-arm64)"},
    {platform_bytecode::kOpcodeRole,               "role chain operation (windows-arm64)"},
    {platform_bytecode::kOpcodeOperatorInput,      "operator yes/no input (windows-arm64)"},
    {platform_bytecode::kOpcodeReturn,             "function return (windows-arm64)"},
    {platform_bytecode::kOpcodeHalt,               "halt VM (windows-arm64)"},
};
#elif TORTURE_PLATFORM_ID == TORTURE_PLATFORM_ANDROID_X86
constexpr DispatchEntry kEntries[] = {
    {platform_bytecode::kOpcodeVerify,             "verify function fingerprint (android-x86)"},
    {platform_bytecode::kOpcodePushInteger,        "push integer constant (android-x86)"},
    {platform_bytecode::kOpcodePushString,         "push string constant (android-x86)"},
    {platform_bytecode::kOpcodePushNull,           "push null literal (android-x86)"},
    {platform_bytecode::kOpcodePushReference,      "push reference to local (android-x86)"},
    {platform_bytecode::kOpcodeDereference,        "dereference reference (android-x86)"},
    {platform_bytecode::kOpcodeFieldReference,     "compute field reference (android-x86)"},
    {platform_bytecode::kOpcodeLoad,               "load local value (android-x86)"},
    {platform_bytecode::kOpcodeStore,              "store local value (android-x86)"},
    {platform_bytecode::kOpcodeStoreDereference,   "store through reference (android-x86)"},
    {platform_bytecode::kOpcodeStorePointer,       "store function pointer (android-x86)"},
    {platform_bytecode::kOpcodePop,                "pop top of stack (android-x86)"},
    {platform_bytecode::kOpcodeAdd,                "integer add (android-x86)"},
    {platform_bytecode::kOpcodeAddTrap,            "integer add trap (android-x86)"},
    {platform_bytecode::kOpcodeAddWrap,            "integer add wrap (android-x86)"},
    {platform_bytecode::kOpcodeAddSaturate,        "integer add saturate (android-x86)"},
    {platform_bytecode::kOpcodeAddExtend,          "integer add extend (android-x86)"},
    {platform_bytecode::kOpcodeSub,                "integer sub (android-x86)"},
    {platform_bytecode::kOpcodeSubTrap,            "integer sub trap (android-x86)"},
    {platform_bytecode::kOpcodeSubWrap,            "integer sub wrap (android-x86)"},
    {platform_bytecode::kOpcodeSubSaturate,        "integer sub saturate (android-x86)"},
    {platform_bytecode::kOpcodeSubExtend,          "integer sub extend (android-x86)"},
    {platform_bytecode::kOpcodeMul,                "integer mul (android-x86)"},
    {platform_bytecode::kOpcodeMulTrap,            "integer mul trap (android-x86)"},
    {platform_bytecode::kOpcodeMulWrap,            "integer mul wrap (android-x86)"},
    {platform_bytecode::kOpcodeMulSaturate,        "integer mul saturate (android-x86)"},
    {platform_bytecode::kOpcodeMulExtend,          "integer mul extend (android-x86)"},
    {platform_bytecode::kOpcodeDiv,                "integer div (android-x86)"},
    {platform_bytecode::kOpcodeDivTrap,            "integer div trap (android-x86)"},
    {platform_bytecode::kOpcodeDivWrap,            "integer div wrap (android-x86)"},
    {platform_bytecode::kOpcodeDivSaturate,        "integer div saturate (android-x86)"},
    {platform_bytecode::kOpcodeDivExtend,          "integer div extend (android-x86)"},
    {platform_bytecode::kOpcodeEqual,              "compare equal (android-x86)"},
    {platform_bytecode::kOpcodeNotEqual,           "compare not equal (android-x86)"},
    {platform_bytecode::kOpcodeLess,               "compare less (android-x86)"},
    {platform_bytecode::kOpcodeLessEqual,          "compare less equal (android-x86)"},
    {platform_bytecode::kOpcodeGreater,            "compare greater (android-x86)"},
    {platform_bytecode::kOpcodeGreaterEqual,       "compare greater equal (android-x86)"},
    {platform_bytecode::kOpcodeAnd,                "logical and (android-x86)"},
    {platform_bytecode::kOpcodeOr,                 "logical or (android-x86)"},
    {platform_bytecode::kOpcodeXor,                "logical xor (android-x86)"},
    {platform_bytecode::kOpcodeNand,               "logical nand (android-x86)"},
    {platform_bytecode::kOpcodeNor,                "logical nor (android-x86)"},
    {platform_bytecode::kOpcodeNot,                "logical not (android-x86)"},
    {platform_bytecode::kOpcodeJump,               "unconditional jump (android-x86)"},
    {platform_bytecode::kOpcodeJumpIfZero,         "jump if zero (android-x86)"},
    {platform_bytecode::kOpcodeCheckApproval,      "check approval gate (android-x86)"},
    {platform_bytecode::kOpcodeCheckLimits,        "check resource limits (android-x86)"},
    {platform_bytecode::kOpcodeCheckRole,          "check role (android-x86)"},
    {platform_bytecode::kOpcodeCheckRoleIndirect,  "check role via pointer (android-x86)"},
    {platform_bytecode::kOpcodeNullCheck,          "null function pointer check (android-x86)"},
    {platform_bytecode::kOpcodeAssert,             "proof obligation assert (android-x86)"},
    {platform_bytecode::kOpcodeCall,               "direct call (android-x86)"},
    {platform_bytecode::kOpcodeCallIndirect,       "indirect call (android-x86)"},
    {platform_bytecode::kOpcodeOutputInt,          "output integer (android-x86)"},
    {platform_bytecode::kOpcodeOutputChar,         "output character (android-x86)"},
    {platform_bytecode::kOpcodePrintLine,          "print line (android-x86)"},
    {platform_bytecode::kOpcodeInputInt,           "input integer (android-x86)"},
    {platform_bytecode::kOpcodeInputChar,          "input character (android-x86)"},
    {platform_bytecode::kOpcodeVerifyEcc,          "verify memory ECC (android-x86)"},
    {platform_bytecode::kOpcodeCopyMemory,         "copy memory (android-x86)"},
    {platform_bytecode::kOpcodeCompareMemory,      "compare memory (android-x86)"},
    {platform_bytecode::kOpcodeRole,               "role chain operation (android-x86)"},
    {platform_bytecode::kOpcodeOperatorInput,      "operator yes/no input (android-x86)"},
    {platform_bytecode::kOpcodeReturn,             "function return (android-x86)"},
    {platform_bytecode::kOpcodeHalt,               "halt VM (android-x86)"},
};
#elif TORTURE_PLATFORM_ID == TORTURE_PLATFORM_ANDROID_X64
constexpr DispatchEntry kEntries[] = {
    {platform_bytecode::kOpcodeVerify,             "verify function fingerprint (android-x64)"},
    {platform_bytecode::kOpcodePushInteger,        "push integer constant (android-x64)"},
    {platform_bytecode::kOpcodePushString,         "push string constant (android-x64)"},
    {platform_bytecode::kOpcodePushNull,           "push null literal (android-x64)"},
    {platform_bytecode::kOpcodePushReference,      "push reference to local (android-x64)"},
    {platform_bytecode::kOpcodeDereference,        "dereference reference (android-x64)"},
    {platform_bytecode::kOpcodeFieldReference,     "compute field reference (android-x64)"},
    {platform_bytecode::kOpcodeLoad,               "load local value (android-x64)"},
    {platform_bytecode::kOpcodeStore,              "store local value (android-x64)"},
    {platform_bytecode::kOpcodeStoreDereference,   "store through reference (android-x64)"},
    {platform_bytecode::kOpcodeStorePointer,       "store function pointer (android-x64)"},
    {platform_bytecode::kOpcodePop,                "pop top of stack (android-x64)"},
    {platform_bytecode::kOpcodeAdd,                "integer add (android-x64)"},
    {platform_bytecode::kOpcodeAddTrap,            "integer add trap (android-x64)"},
    {platform_bytecode::kOpcodeAddWrap,            "integer add wrap (android-x64)"},
    {platform_bytecode::kOpcodeAddSaturate,        "integer add saturate (android-x64)"},
    {platform_bytecode::kOpcodeAddExtend,          "integer add extend (android-x64)"},
    {platform_bytecode::kOpcodeSub,                "integer sub (android-x64)"},
    {platform_bytecode::kOpcodeSubTrap,            "integer sub trap (android-x64)"},
    {platform_bytecode::kOpcodeSubWrap,            "integer sub wrap (android-x64)"},
    {platform_bytecode::kOpcodeSubSaturate,        "integer sub saturate (android-x64)"},
    {platform_bytecode::kOpcodeSubExtend,          "integer sub extend (android-x64)"},
    {platform_bytecode::kOpcodeMul,                "integer mul (android-x64)"},
    {platform_bytecode::kOpcodeMulTrap,            "integer mul trap (android-x64)"},
    {platform_bytecode::kOpcodeMulWrap,            "integer mul wrap (android-x64)"},
    {platform_bytecode::kOpcodeMulSaturate,        "integer mul saturate (android-x64)"},
    {platform_bytecode::kOpcodeMulExtend,          "integer mul extend (android-x64)"},
    {platform_bytecode::kOpcodeDiv,                "integer div (android-x64)"},
    {platform_bytecode::kOpcodeDivTrap,            "integer div trap (android-x64)"},
    {platform_bytecode::kOpcodeDivWrap,            "integer div wrap (android-x64)"},
    {platform_bytecode::kOpcodeDivSaturate,        "integer div saturate (android-x64)"},
    {platform_bytecode::kOpcodeDivExtend,          "integer div extend (android-x64)"},
    {platform_bytecode::kOpcodeEqual,              "compare equal (android-x64)"},
    {platform_bytecode::kOpcodeNotEqual,           "compare not equal (android-x64)"},
    {platform_bytecode::kOpcodeLess,               "compare less (android-x64)"},
    {platform_bytecode::kOpcodeLessEqual,          "compare less equal (android-x64)"},
    {platform_bytecode::kOpcodeGreater,            "compare greater (android-x64)"},
    {platform_bytecode::kOpcodeGreaterEqual,       "compare greater equal (android-x64)"},
    {platform_bytecode::kOpcodeAnd,                "logical and (android-x64)"},
    {platform_bytecode::kOpcodeOr,                 "logical or (android-x64)"},
    {platform_bytecode::kOpcodeXor,                "logical xor (android-x64)"},
    {platform_bytecode::kOpcodeNand,               "logical nand (android-x64)"},
    {platform_bytecode::kOpcodeNor,                "logical nor (android-x64)"},
    {platform_bytecode::kOpcodeNot,                "logical not (android-x64)"},
    {platform_bytecode::kOpcodeJump,               "unconditional jump (android-x64)"},
    {platform_bytecode::kOpcodeJumpIfZero,         "jump if zero (android-x64)"},
    {platform_bytecode::kOpcodeCheckApproval,      "check approval gate (android-x64)"},
    {platform_bytecode::kOpcodeCheckLimits,        "check resource limits (android-x64)"},
    {platform_bytecode::kOpcodeCheckRole,          "check role (android-x64)"},
    {platform_bytecode::kOpcodeCheckRoleIndirect,  "check role via pointer (android-x64)"},
    {platform_bytecode::kOpcodeNullCheck,          "null function pointer check (android-x64)"},
    {platform_bytecode::kOpcodeAssert,             "proof obligation assert (android-x64)"},
    {platform_bytecode::kOpcodeCall,               "direct call (android-x64)"},
    {platform_bytecode::kOpcodeCallIndirect,       "indirect call (android-x64)"},
    {platform_bytecode::kOpcodeOutputInt,          "output integer (android-x64)"},
    {platform_bytecode::kOpcodeOutputChar,         "output character (android-x64)"},
    {platform_bytecode::kOpcodePrintLine,          "print line (android-x64)"},
    {platform_bytecode::kOpcodeInputInt,           "input integer (android-x64)"},
    {platform_bytecode::kOpcodeInputChar,          "input character (android-x64)"},
    {platform_bytecode::kOpcodeVerifyEcc,          "verify memory ECC (android-x64)"},
    {platform_bytecode::kOpcodeCopyMemory,         "copy memory (android-x64)"},
    {platform_bytecode::kOpcodeCompareMemory,      "compare memory (android-x64)"},
    {platform_bytecode::kOpcodeRole,               "role chain operation (android-x64)"},
    {platform_bytecode::kOpcodeOperatorInput,      "operator yes/no input (android-x64)"},
    {platform_bytecode::kOpcodeReturn,             "function return (android-x64)"},
    {platform_bytecode::kOpcodeHalt,               "halt VM (android-x64)"},
};
#elif TORTURE_PLATFORM_ID == TORTURE_PLATFORM_ANDROID_ARM32
constexpr DispatchEntry kEntries[] = {
    {platform_bytecode::kOpcodeVerify,             "verify function fingerprint (android-arm32)"},
    {platform_bytecode::kOpcodePushInteger,        "push integer constant (android-arm32)"},
    {platform_bytecode::kOpcodePushString,         "push string constant (android-arm32)"},
    {platform_bytecode::kOpcodePushNull,           "push null literal (android-arm32)"},
    {platform_bytecode::kOpcodePushReference,      "push reference to local (android-arm32)"},
    {platform_bytecode::kOpcodeDereference,        "dereference reference (android-arm32)"},
    {platform_bytecode::kOpcodeFieldReference,     "compute field reference (android-arm32)"},
    {platform_bytecode::kOpcodeLoad,               "load local value (android-arm32)"},
    {platform_bytecode::kOpcodeStore,              "store local value (android-arm32)"},
    {platform_bytecode::kOpcodeStoreDereference,   "store through reference (android-arm32)"},
    {platform_bytecode::kOpcodeStorePointer,       "store function pointer (android-arm32)"},
    {platform_bytecode::kOpcodePop,                "pop top of stack (android-arm32)"},
    {platform_bytecode::kOpcodeAdd,                "integer add (android-arm32)"},
    {platform_bytecode::kOpcodeAddTrap,            "integer add trap (android-arm32)"},
    {platform_bytecode::kOpcodeAddWrap,            "integer add wrap (android-arm32)"},
    {platform_bytecode::kOpcodeAddSaturate,        "integer add saturate (android-arm32)"},
    {platform_bytecode::kOpcodeAddExtend,          "integer add extend (android-arm32)"},
    {platform_bytecode::kOpcodeSub,                "integer sub (android-arm32)"},
    {platform_bytecode::kOpcodeSubTrap,            "integer sub trap (android-arm32)"},
    {platform_bytecode::kOpcodeSubWrap,            "integer sub wrap (android-arm32)"},
    {platform_bytecode::kOpcodeSubSaturate,        "integer sub saturate (android-arm32)"},
    {platform_bytecode::kOpcodeSubExtend,          "integer sub extend (android-arm32)"},
    {platform_bytecode::kOpcodeMul,                "integer mul (android-arm32)"},
    {platform_bytecode::kOpcodeMulTrap,            "integer mul trap (android-arm32)"},
    {platform_bytecode::kOpcodeMulWrap,            "integer mul wrap (android-arm32)"},
    {platform_bytecode::kOpcodeMulSaturate,        "integer mul saturate (android-arm32)"},
    {platform_bytecode::kOpcodeMulExtend,          "integer mul extend (android-arm32)"},
    {platform_bytecode::kOpcodeDiv,                "integer div (android-arm32)"},
    {platform_bytecode::kOpcodeDivTrap,            "integer div trap (android-arm32)"},
    {platform_bytecode::kOpcodeDivWrap,            "integer div wrap (android-arm32)"},
    {platform_bytecode::kOpcodeDivSaturate,        "integer div saturate (android-arm32)"},
    {platform_bytecode::kOpcodeDivExtend,          "integer div extend (android-arm32)"},
    {platform_bytecode::kOpcodeEqual,              "compare equal (android-arm32)"},
    {platform_bytecode::kOpcodeNotEqual,           "compare not equal (android-arm32)"},
    {platform_bytecode::kOpcodeLess,               "compare less (android-arm32)"},
    {platform_bytecode::kOpcodeLessEqual,          "compare less equal (android-arm32)"},
    {platform_bytecode::kOpcodeGreater,            "compare greater (android-arm32)"},
    {platform_bytecode::kOpcodeGreaterEqual,       "compare greater equal (android-arm32)"},
    {platform_bytecode::kOpcodeAnd,                "logical and (android-arm32)"},
    {platform_bytecode::kOpcodeOr,                 "logical or (android-arm32)"},
    {platform_bytecode::kOpcodeXor,                "logical xor (android-arm32)"},
    {platform_bytecode::kOpcodeNand,               "logical nand (android-arm32)"},
    {platform_bytecode::kOpcodeNor,                "logical nor (android-arm32)"},
    {platform_bytecode::kOpcodeNot,                "logical not (android-arm32)"},
    {platform_bytecode::kOpcodeJump,               "unconditional jump (android-arm32)"},
    {platform_bytecode::kOpcodeJumpIfZero,         "jump if zero (android-arm32)"},
    {platform_bytecode::kOpcodeCheckApproval,      "check approval gate (android-arm32)"},
    {platform_bytecode::kOpcodeCheckLimits,        "check resource limits (android-arm32)"},
    {platform_bytecode::kOpcodeCheckRole,          "check role (android-arm32)"},
    {platform_bytecode::kOpcodeCheckRoleIndirect,  "check role via pointer (android-arm32)"},
    {platform_bytecode::kOpcodeNullCheck,          "null function pointer check (android-arm32)"},
    {platform_bytecode::kOpcodeAssert,             "proof obligation assert (android-arm32)"},
    {platform_bytecode::kOpcodeCall,               "direct call (android-arm32)"},
    {platform_bytecode::kOpcodeCallIndirect,       "indirect call (android-arm32)"},
    {platform_bytecode::kOpcodeOutputInt,          "output integer (android-arm32)"},
    {platform_bytecode::kOpcodeOutputChar,         "output character (android-arm32)"},
    {platform_bytecode::kOpcodePrintLine,          "print line (android-arm32)"},
    {platform_bytecode::kOpcodeInputInt,           "input integer (android-arm32)"},
    {platform_bytecode::kOpcodeInputChar,          "input character (android-arm32)"},
    {platform_bytecode::kOpcodeVerifyEcc,          "verify memory ECC (android-arm32)"},
    {platform_bytecode::kOpcodeCopyMemory,         "copy memory (android-arm32)"},
    {platform_bytecode::kOpcodeCompareMemory,      "compare memory (android-arm32)"},
    {platform_bytecode::kOpcodeRole,               "role chain operation (android-arm32)"},
    {platform_bytecode::kOpcodeOperatorInput,      "operator yes/no input (android-arm32)"},
    {platform_bytecode::kOpcodeReturn,             "function return (android-arm32)"},
    {platform_bytecode::kOpcodeHalt,               "halt VM (android-arm32)"},
};
#elif TORTURE_PLATFORM_ID == TORTURE_PLATFORM_ANDROID_ARM64
constexpr DispatchEntry kEntries[] = {
    {platform_bytecode::kOpcodeVerify,             "verify function fingerprint (android-arm64)"},
    {platform_bytecode::kOpcodePushInteger,        "push integer constant (android-arm64)"},
    {platform_bytecode::kOpcodePushString,         "push string constant (android-arm64)"},
    {platform_bytecode::kOpcodePushNull,           "push null literal (android-arm64)"},
    {platform_bytecode::kOpcodePushReference,      "push reference to local (android-arm64)"},
    {platform_bytecode::kOpcodeDereference,        "dereference reference (android-arm64)"},
    {platform_bytecode::kOpcodeFieldReference,     "compute field reference (android-arm64)"},
    {platform_bytecode::kOpcodeLoad,               "load local value (android-arm64)"},
    {platform_bytecode::kOpcodeStore,              "store local value (android-arm64)"},
    {platform_bytecode::kOpcodeStoreDereference,   "store through reference (android-arm64)"},
    {platform_bytecode::kOpcodeStorePointer,       "store function pointer (android-arm64)"},
    {platform_bytecode::kOpcodePop,                "pop top of stack (android-arm64)"},
    {platform_bytecode::kOpcodeAdd,                "integer add (android-arm64)"},
    {platform_bytecode::kOpcodeAddTrap,            "integer add trap (android-arm64)"},
    {platform_bytecode::kOpcodeAddWrap,            "integer add wrap (android-arm64)"},
    {platform_bytecode::kOpcodeAddSaturate,        "integer add saturate (android-arm64)"},
    {platform_bytecode::kOpcodeAddExtend,          "integer add extend (android-arm64)"},
    {platform_bytecode::kOpcodeSub,                "integer sub (android-arm64)"},
    {platform_bytecode::kOpcodeSubTrap,            "integer sub trap (android-arm64)"},
    {platform_bytecode::kOpcodeSubWrap,            "integer sub wrap (android-arm64)"},
    {platform_bytecode::kOpcodeSubSaturate,        "integer sub saturate (android-arm64)"},
    {platform_bytecode::kOpcodeSubExtend,          "integer sub extend (android-arm64)"},
    {platform_bytecode::kOpcodeMul,                "integer mul (android-arm64)"},
    {platform_bytecode::kOpcodeMulTrap,            "integer mul trap (android-arm64)"},
    {platform_bytecode::kOpcodeMulWrap,            "integer mul wrap (android-arm64)"},
    {platform_bytecode::kOpcodeMulSaturate,        "integer mul saturate (android-arm64)"},
    {platform_bytecode::kOpcodeMulExtend,          "integer mul extend (android-arm64)"},
    {platform_bytecode::kOpcodeDiv,                "integer div (android-arm64)"},
    {platform_bytecode::kOpcodeDivTrap,            "integer div trap (android-arm64)"},
    {platform_bytecode::kOpcodeDivWrap,            "integer div wrap (android-arm64)"},
    {platform_bytecode::kOpcodeDivSaturate,        "integer div saturate (android-arm64)"},
    {platform_bytecode::kOpcodeDivExtend,          "integer div extend (android-arm64)"},
    {platform_bytecode::kOpcodeEqual,              "compare equal (android-arm64)"},
    {platform_bytecode::kOpcodeNotEqual,           "compare not equal (android-arm64)"},
    {platform_bytecode::kOpcodeLess,               "compare less (android-arm64)"},
    {platform_bytecode::kOpcodeLessEqual,          "compare less equal (android-arm64)"},
    {platform_bytecode::kOpcodeGreater,            "compare greater (android-arm64)"},
    {platform_bytecode::kOpcodeGreaterEqual,       "compare greater equal (android-arm64)"},
    {platform_bytecode::kOpcodeAnd,                "logical and (android-arm64)"},
    {platform_bytecode::kOpcodeOr,                 "logical or (android-arm64)"},
    {platform_bytecode::kOpcodeXor,                "logical xor (android-arm64)"},
    {platform_bytecode::kOpcodeNand,               "logical nand (android-arm64)"},
    {platform_bytecode::kOpcodeNor,                "logical nor (android-arm64)"},
    {platform_bytecode::kOpcodeNot,                "logical not (android-arm64)"},
    {platform_bytecode::kOpcodeJump,               "unconditional jump (android-arm64)"},
    {platform_bytecode::kOpcodeJumpIfZero,         "jump if zero (android-arm64)"},
    {platform_bytecode::kOpcodeCheckApproval,      "check approval gate (android-arm64)"},
    {platform_bytecode::kOpcodeCheckLimits,        "check resource limits (android-arm64)"},
    {platform_bytecode::kOpcodeCheckRole,          "check role (android-arm64)"},
    {platform_bytecode::kOpcodeCheckRoleIndirect,  "check role via pointer (android-arm64)"},
    {platform_bytecode::kOpcodeNullCheck,          "null function pointer check (android-arm64)"},
    {platform_bytecode::kOpcodeAssert,             "proof obligation assert (android-arm64)"},
    {platform_bytecode::kOpcodeCall,               "direct call (android-arm64)"},
    {platform_bytecode::kOpcodeCallIndirect,       "indirect call (android-arm64)"},
    {platform_bytecode::kOpcodeOutputInt,          "output integer (android-arm64)"},
    {platform_bytecode::kOpcodeOutputChar,         "output character (android-arm64)"},
    {platform_bytecode::kOpcodePrintLine,          "print line (android-arm64)"},
    {platform_bytecode::kOpcodeInputInt,           "input integer (android-arm64)"},
    {platform_bytecode::kOpcodeInputChar,          "input character (android-arm64)"},
    {platform_bytecode::kOpcodeVerifyEcc,          "verify memory ECC (android-arm64)"},
    {platform_bytecode::kOpcodeCopyMemory,         "copy memory (android-arm64)"},
    {platform_bytecode::kOpcodeCompareMemory,      "compare memory (android-arm64)"},
    {platform_bytecode::kOpcodeRole,               "role chain operation (android-arm64)"},
    {platform_bytecode::kOpcodeOperatorInput,      "operator yes/no input (android-arm64)"},
    {platform_bytecode::kOpcodeReturn,             "function return (android-arm64)"},
    {platform_bytecode::kOpcodeHalt,               "halt VM (android-arm64)"},
};
#else
  #error "TORTURE_PLATFORM_ID does not match any of the 12 supported platforms"
#endif

const std::unordered_map<std::uint16_t, const char*>& dispatchTable() {
    static const std::unordered_map<std::uint16_t, const char*> table = []() {
        std::unordered_map<std::uint16_t, const char*> built;
        built.reserve(sizeof(kEntries) / sizeof(kEntries[0]));
        for (const auto& entry : kEntries) {
            built.emplace(entry.id, entry.description);
        }
        return built;
    }();
    return table;
}

bool isOwnPlatformOpcode(std::uint16_t id) {
    if (static_cast<std::uint8_t>(id >> 8) != TORTURE_PLATFORM_ID) {
        return false;
    }
    const auto local = static_cast<std::uint16_t>(id & 0xFFu);
    return local >= 0x01 && local <= 0x42;
}

}  // namespace torture::vm::platform_vm
